version: '3.4'

networks:
  userapitesttaskvk-back-network:
    driver: bridge

services:
  userapitesttaskvk.api:
    container_name: userapitesttaskvk.api
    image: ${DOCKER_REGISTRY-}userapitesttaskvkapi
    build:
      context: .
      dockerfile: src/UserApiTestTaskVk.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - AppSettings__AllowedOrigin=http://localhost:8081
      - ConnectionStrings__Db=Host=userapitesttaskvk.db;Port=5432;Database=postgres;Username=postgres;Password=example
      - JwtConfig__AccessTokenLifeTime=600
    depends_on:
      - userapitesttaskvk.db
    networks:
      - userapitesttaskvk-back-network
    restart: on-failure

  userapitesttaskvk.db:
    container_name: userapitesttaskvk.db
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - userapitesttaskvk-back-network
    volumes:
      - ..\UserApiTestTaskVk.Volumes\Postgres:/var/lib/postgresql/data
    restart: on-failure
